name: Auto Update Geetest Logic
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须开启写入权限
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install requests
          
      - name: Run Deobfuscator
        id: run_script
        run: |
          output=$(python deobfuscate.py)
          echo "VERSION=$(echo "$output" | grep '\[~\] Version:' | awk '{print $3}')" >> $GITHUB_ENV
          echo "ABO=$(echo "$output" | grep '\[+\] abo:' | sed 's/.*: //')" >> $GITHUB_ENV
          echo "MAPPINGS=$(echo "$output" | grep '\[+\] mappings' | sed 's/\[+\] mappings //')" >> $GITHUB_ENV
          echo "DEVICE_ID=$(echo "$output" | grep '\[+\] device_id:' | sed -n 's/.*: \(\"[^\"]*\"\).*/\1/p')" >> $GITHUB_ENV

      - name: Force Update Logic Files
        run: |
          # 强制替换 sign.py 里的动态常量
          sed -i "s|self.mapping = {.*}|self.mapping = $MAPPINGS|" ./geeked/sign.py
          sed -i "s|abo = {.*}|abo = $ABO|" ./geeked/sign.py
          sed -i "s|\"device_id\": \".*\"|\"device_id\": $DEVICE_ID|" ./geeked/sign.py

      - name: Auto Push to Main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # 只有在有变化时才提交，防止报错
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 自动同步极验算法: ${{ env.VERSION }}" && git push)
